kind: Deployment
apiVersion: apps/v1
metadata:
   name: krishna
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to kittu
    matchLabels:
     app: krishna
   template:
      metadata:
        labels:
          app: krishna
      spec:
       containers:
        - name: krishna
          image: kittu1993/project_demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
