kind: Service                             
apiVersion: v1
metadata:
  name: krishna
  labels:
    app: krishna
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31300
  selector:
    app: krishna                    
  type: LoadBalancer                   
